---
- hosts: 172.31.19.214
  become: yes
  tasks:
  - name: execute linux directly
    command:  hostname -f
    register: myresult

  - name: i want to display first task result
    debug:
     msg: "{{myresult}}"